name: production-integration

on: 
  schedule:
   - cron:  '*/60 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: Install Chrome Standalone
      uses: selenium/standalone-chrome
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests nose2 selenium
    - name: Test with pytest
      run: |
        cd test-production-integration	&& nose2 -v test_selenium
