name: production-integration

on: 
  schedule:
   - cron:  '*/60 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      chrome:
        image: selenium/standalone-chrome:3.141.59-20200326
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - "4444:4444"           
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests nose2 selenium
    - name: Test with pytest
      run: |
        cd test-production-integration	&& nose2 -v test_selenium
