name: production-integration

on: 
  schedule:
   - cron:  '*/60 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
        python -m pip install --upgrade pip
        pip install requests nose2 selenium
    - name: Test with pytest
      run: |
        cd test-production-integration	&& nose2 -v test_selenium
